# Generated by Django 2.2 on 2020-05-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotesTry1',
        ),
    ]
