# Generated by Django 2.2 on 2020-05-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes_api', '0002_delete_notestry1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesTry1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=200)),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_api.NotesTry1')),
            ],
        ),
    ]
